name: Deploy to GitHub Pages

on:
  push:
    branches: [main]        # déploie à chaque push sur main
  workflow_dispatch:        # bouton « Run workflow » manuel

permissions:
  contents: read            # lire le repo
  pages: write              # publier sur GitHub Pages
  id-token: write           # authenticité OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4               # ← nouveau

      - name: Install, build, and upload
        uses: withastro/action@v4               # ← nouveau
        # with:
        #   node-version: 22                   # optionnel : version précise

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4          # ← nouveau
